- name: Configure webserver no TLS
  hosts: webservers
  become: True
  tasks:
   - name: install Nginx
     apt: name=nginx update_cache=yes

   - name: copy config
     copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
  
   - name: enable configuration via symlink
     file: >
       dest=/etc/nginx/sites-enabled/default
       src=/etc/nginx/sites-available/default
       state=link

   - name: copy index file
     template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  
   - name: restart Nginx
     service: name=nginx state=restarted